include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    # Error rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Style rules
    always_declare_return_types: true
    always_use_package_imports: false
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"